server:
  port: 9999
  servlet:
    context-path: /luckymoney/xj

limit:
  minMoney: 0.01
  maxMoney: 99
  description: 最少要发${limit.minMoney}元，最多发${limit.maxMoney}元

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luckymoney?serverTimezone=UTC
    #连接后面加上“?serverTimezone=UTC”，否则乱码，并报错
    username: root
    password: 282013
  jpa:
    hibernate:
      ddl-auto: update
      #这里如果是create，每次会重新建表，所以改为update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #设置正确的Hibernate SQL方言，这里的mysql版本5，不能缺省，否则报错；这里5后面不加InnoDB的话，默认是MyISAM。